services:
  - docker

script:
 #- bash delete.sh $DOCKER_USER $DOCKER_PASS
  - docker build -t nginx .
  - docker tag nginx $DOCKER_USERNAME/nginx:latest
  - bash installGoogleContDiff.sh $DOCKER_USER $DOCKER_PASS